# Model parameters.
model:
  model: "SUNet18" 
  2d_loss: 'bce' 
  # 3d_loss: 'mse' 
  exclude_zeros: False
  num_classes: 2
  pretraining_strategy: "imagenet"
  feature_extractor_arch: "resnet18" 
  checkpoints_path:
  loss_weights: [1, 3]
  2d_loss_weights: [0.05, 0.95]
  class_ignored: 9999 
  restore_checkpoints: '3d' 

# Optimization parameters.
optim:
  num_epochs: 101
  lr: 0.0001
  optim_type: "adamw" 
  momentum: 0.9
  nesterov: False
  beta: [0.9, 0.999]
  end_lr: 0.000005
  weight_decay: 0.001
  lr_schedule_type: "step_lr"
  step: 300 
  gamma: 0.75
  last_epoch: 10

# Data parameters:
data:
  dataset_name: 'SECOND'
  max_value: 30
  min_value: -25
  augmentations: True
  #BCDD
  mean: [0.43619737, 0.44344816, 0.45402834]
  std: [0.15784438, 0.14617704, 0.1445269]
  train:
    path: '/dataset/SECOND_fs/'
    batch_size: 32
